In [ ]:
#3.1

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [3]:
dataset = 'SaYoPillow.csv'

In [4]:
data = pd.read_csv(dataset)

In [5]:
data.head()

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [6]:
X = data.drop('sl', axis=1)
y = data['sl']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(X_train.shape[1],), activation='relu'),
    tf.keras.layers.Dense(6, activation='softmax')
])

In [10]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [11]:
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1)

Epoch 1/100


441/441 [==============================] - 1s 1ms/step - loss: 1.6850 - accuracy: 0.3039
Epoch 2/100
441/441 [==============================] - 0s 1ms/step - loss: 1.0998 - accuracy: 0.5420
Epoch 3/100
441/441 [==============================] - 0s 1ms/step - loss: 0.7572 - accuracy: 0.7438
Epoch 4/100
441/441 [==============================] - 0s 999us/step - loss: 0.5195 - accuracy: 0.8277
Epoch 5/100
441/441 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.9592
Epoch 6/100
441/441 [==============================] - 0s 1ms/step - loss: 0.2208 - accuracy: 1.0000
Epoch 7/100
441/441 [==============================] - 0s 945us/step - loss: 0.1477 - accuracy: 1.0000
Epoch 8/100
441/441 [==============================] - 0s 1ms/step - loss: 0.1020 - accuracy: 1.0000
Epoch 9/100
441/441 [==============================] - 0s 1ms/step - loss: 0.0721 - accuracy: 1.0000
Epoch 10/100
441/441 [==============================] - 0s 1ms/step - loss: 0.0518 - 

441/441 [==============================] - 0s 1ms/step - loss: 3.7304e-08 - accuracy: 1.0000
Epoch 75/100
441/441 [==============================] - 0s 853us/step - loss: 2.8113e-08 - accuracy: 1.0000
Epoch 76/100
441/441 [==============================] - 0s 859us/step - loss: 2.8113e-08 - accuracy: 1.0000
Epoch 77/100
441/441 [==============================] - 0s 817us/step - loss: 2.5410e-08 - accuracy: 1.0000
Epoch 78/100
441/441 [==============================] - 0s 799us/step - loss: 2.1625e-08 - accuracy: 1.0000
Epoch 79/100
441/441 [==============================] - 0s 814us/step - loss: 1.5678e-08 - accuracy: 1.0000
Epoch 80/100
441/441 [==============================] - 0s 882us/step - loss: 1.4597e-08 - accuracy: 1.0000
Epoch 81/100
441/441 [==============================] - 0s 801us/step - loss: 1.2164e-08 - accuracy: 1.0000
Epoch 82/100
441/441 [==============================] - 0s 848us/step - loss: 1.0272e-08 - accuracy: 1.0000
Epoch 83/100
441/441 [=====================

In [14]:
y_pred = np.argmax(model.predict(X_test), axis=1)
print(classification_report(y_test, y_pred))

6/6 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      1.00      1.00        38
           2       1.00      1.00      1.00        39
           3       1.00      1.00      1.00        33
           4       1.00      1.00      1.00        42

    accuracy                           1.00       189
   macro avg       1.00      1.00      1.00       189
weighted avg       1.00      1.00      1.00       189



In [15]:
print(confusion_matrix(y_test, y_pred))

[[37  0  0  0  0]
 [ 0 38  0  0  0]
 [ 0  0 39  0  0]
 [ 0  0  0 33  0]
 [ 0  0  0  0 42]]
